central:
  Bu_Kee_eq_btosllball05_DPC :
    model:
      - dscb
    shared:
      - mu
      - sg
  Bu_JpsiK_ee_eq_DPC:
    model:
      - kde 
    shared: []
  Bd_Kstee_eq_btosllball05_DPC:
    model:
      - dscb
    shared: []
  Bu_Kstee_Kpi0_eq_btosllball05_DPC:
    model:
      - dscb
    shared: []
